#pragma once
#include <Day0.hxx>
#include <Day1.hxx>
#include <Day2.hxx>
#include <Day3.hxx>
#include <Day4.hxx>
#include <Day5.hxx>
#include <Day6.hxx>
#include <Day7.hxx>
#include <Day8.hxx>
#include <Day9.hxx>
